"""empty message

Revision ID: 5e37b7dd9f7e
Revises: a56ffedf9129
Create Date: 2026-05-04 02:58:53.332029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e37b7dd9f7e'
down_revision = 'a56ffedf9129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_urls', sa.JSON(), nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('photo_urls')

    # ### end Alembic commands ###
