"""cambiando profile_picture a text para soportar base64

Revision ID: 712c2a759b21
Revises: 1b5441509ebd
Create Date: 2026-04-23 03:38:00.501823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712c2a759b21'
down_revision = '1b5441509ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
